**Importing Libraries**

---

In [ ]:
import numpy as np
import pandas as pd

n1 = np.array([[3,5,7,8], [3,2,1,3], [2,1,8,4], [5,2,1,8]])
print(n1)

[[3 5 7 8]
 [3 2 1 3]
 [2 1 8 4]
 [5 2 1 8]]

In [ ]:
p1 = pd.DataFrame(n1, columns=['a','b','c','d'])
p1.index = [1,2,3,4]
p1

   a  b  c  d
1  3  5  7  8
2  3  2  1  3
3  2  1  8  4
4  5  2  1  8

In [ ]:
p1.dtypes

a    int64
b    int64
c    int64
d    int64
dtype: object

In [ ]:
p1['d'][2] = '$3'

In [ ]:
p1.dtypes

a     int64
b     int64
c     int64
d    object
dtype: object

In [ ]:
p1

   a  b  c   d
1  3  5  7   8
2  3  2  1  $3
3  2  1  8   4
4  5  2  1   8

In [ ]:
p1[['a']]

   a
1  3
2  3
3  2
4  5

In [ ]:
p1[['a','c']]

   a  c
1  3  7
2  3  1
3  2  8
4  5  1

In [ ]:
p1.loc[2:4, :]

   a  b  c   d
2  3  2  1  $3
3  2  1  8   4
4  5  2  1   8

In [ ]:
p1.loc[:, 'b':'d']

   b  c   d
1  5  7   8
2  2  1  $3
3  1  8   4
4  2  1   8

In [ ]:
p1.loc[[2,4], ['b','d']]

   b   d
2  2  $3
4  2   8

In [ ]:
p1.loc[2:4, 'b':'d']

   b  c   d
2  2  1  $3
3  1  8   4
4  2  1   8

In [ ]:
#iloc: [initial location: initial location+total numbers of columns
p1.iloc[0:3, 1:1+3]

   b  c   d
1  5  7   8
2  2  1  $3
3  1  8   4

In [ ]:
p1.iloc[2:3, 1:2] = 45

In [ ]:
p1

   a   b  c   d
1  3   5  7   8
2  3   2  1  $3
3  2  45  8   4
4  5   2  1   8

In [ ]:
p1['e'] = [4,3,2,1]

In [ ]:
p1

   a   b  c   d  e
1  3   5  7   8  4
2  3   2  1  $3  3
3  2  45  8   4  2
4  5   2  1   8  1

In [ ]:
p1.loc[3,'a'] = 22

In [ ]:
p1

    a   b  c   d  e
1   3   5  7   8  4
2   3   2  1  $3  3
3  22  45  8   4  2
4   5   2  1   8  1

In [ ]:
p1['c'][4] = 11

In [29]:
p1

    a   b   c   d  e
1   3   5   7   8  4
2   3   2   1  $3  3
3  22  45   8   4  2
4   5   2  11   8  1

In [30]:
p1.iloc[2:2+2, :]

    a   b   c  d  e
3  22  45   8  4  2
4   5   2  11  8  1

In [31]:
p1.iloc[1:3, :]

    a   b  c   d  e
2   3   2  1  $3  3
3  22  45  8   4  2